version: '3.1'

services:
    main:
        build:
            .\main
        restart: always
        ports:
            - 10000:10000
    login:
        build:
            .\login-microservice
        restart: always
        ports:
            - 11000:11000
    user:
        build:
            .\user-microservice
        restart: always
        ports:
            - 12000:12000
    cameras:
        build:
            .\cameras_microservice
        restart: always
        ports:
            - 16000:16000
