version: '3.1'

services:
    main:
        build:
            .\main
        restart: always
        ports:
            - 10000:10000
    login:
        build:
            .\login-microservice
        restart: always
        ports:
            - 11000:11000
    new_user:
        build:
            .\new-user-microservice
        restart: always
        ports:
            - 12000:12000