version: '3.1'

services:
    main:
        build:
            .\main
        restart: always
        ports:
            - 10000:10000
    login:
        build:
            .\login-microservice
        restart: always
        ports:
            - 11000:11000
    new_user:
        build:
            .\user\new-user-microservice
        restart: always
        ports:
            - 12000:12000
    user_table:
        build:
            .\user\user-table-microservice
        restart: always
        ports:
            - 13000:13000